version: "3.0"
services:
  database:
    image: mdillon/postgis
    ports:
      - "5402:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: openomni
      POSTGRES_USER: openomni

  web:
    build: ./web
    ports:
      - "8112:8000"
    links:
      - database:database
    environment:
      DB_NAME: openomni
      DB_PASSWORD: insecure
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "openomni.wsgi:application"
      UWSGI_PROCESSES: 4
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/openomni/static=/static"