# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'action',
            },
        ),
        migrations.CreateModel(
            name='RawCapture',
            fields=[
                ('cap_id', models.AutoField(primary_key=True, serialize=False)),
                ('RawCapture', models.CharField(max_length=255, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_name', to='openomni.Action')),
            ],
            options={
                'db_table': 'capture_raw',
            },
        ),
    ]
