# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 23:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openomni', '0002_action_date_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
